# -*- coding: utf-8 -*-
"""Tienda_Aurelion_Programa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQy63P_2dBwrxzMjn8l_bvuS9DhM2VBv
"""

!pip install numpy

import numpy as np
import pandas as pd

import pandas as pd


class RetailDataAnalyzer:
    def __init__(self, clientes_path, productos_path, ventas_path, detalle_path):
        self.paths = {
            "clientes": clientes_path,
            "productos": productos_path,
            "ventas": ventas_path,
            "detalle_ventas": detalle_path
        }
        self.dataframes = {}
        self.data_analitica = None
    # Preparación de datos

    def preparar_datos(self):
        self.dataframes["clientes"] = pd.read_excel(self.paths["clientes"])
        self.dataframes["productos"] = pd.read_excel(self.paths["productos"])
        self.dataframes["ventas"] = pd.read_excel(
            self.paths["ventas"], parse_dates=["fecha"]
        )
        self.dataframes["detalle_ventas"] = pd.read_excel(self.paths["detalle_ventas"])

        # Limpieza básica
        for df in self.dataframes.values():
            df.dropna(inplace=True)

        # Integración
        ventas_clientes = pd.merge(
            self.dataframes["ventas"],
            self.dataframes["clientes"],
            on="id_cliente",
            how="inner"
        )

        detalle_productos = pd.merge(
            self.dataframes["detalle_ventas"],
            self.dataframes["productos"],
            on="id_producto",
            how="inner"
        )

        self.data_analitica = pd.merge(
            ventas_clientes,
            detalle_productos,
            on="id_venta",
            how="inner"
        )

    # Opciones del menú
    def info_conjunto_datos(self):
        print("\n Información del conjunto de datos")
        print(f"Total de archivos utilizados: {len(self.dataframes)}\n")

        for nombre, df in self.dataframes.items():
            print(f" {nombre.upper()}")
            print(f"Registros: {df.shape[0]} | Columnas: {df.shape[1]}")
            print("Tipos de datos:")
            print(df.dtypes)
            print("-" * 40)

    def resumen_general(self):
        ventas_totales = self.data_analitica["importe"].sum()
        ticket_promedio = (
            self.data_analitica.groupby("id_venta")["importe"].sum().mean()
        )

        print("\nResumen General de Ventas")
        print(f"Ventas totales: ${ventas_totales:,.2f}")
        print(f"Ticket promedio: ${ticket_promedio:,.2f}")

    def ventas_por_categoria(self):
        print("\n Ventas por Categoría")
        print(
            self.data_analitica
            .groupby("categoria")["importe"]
            .sum()
            .sort_values(ascending=False)
        )
    # Menú interactivo
    def mostrar_menu(self):
        print("\n==*==*= MENÚ PRINCIPAL ==*==*=")
        print("1. Información del conjunto de datos")
        print("2. Resumen general de ventas")
        print("3. Ventas por categoría")
        print("4. Salir")

    def ejecutar_menu(self):
        self.preparar_datos()
        opcion = ""

        while opcion != "4":
            self.mostrar_menu()
            opcion = input("Seleccione una opción: ")

            if opcion == "1":
                self.info_conjunto_datos()
            elif opcion == "2":
                self.resumen_general()
            elif opcion == "3":
                self.ventas_por_categoria()
            elif opcion == "4":
                print("\n Programa finalizado \n Vuelve pronto.")
            else:
                print("\n Opción no válida. Intente nuevamente.")


analizador = RetailDataAnalyzer(
    clientes_path="clientes.xlsx",
    productos_path="productos.xlsx",
    ventas_path="ventas.xlsx",
    detalle_path="detalle_ventas.xlsx"
)

analizador.ejecutar_menu()

